language: php

php:
  - '7.1.3'

install:
  - curl -sSfL -o composer.phar https://getcomposer.org/composer-stable.phar
  - curl -sSfL -o phar-composer.phar https://github.com/clue/phar-composer/releases/download/v1.1.0/phar-composer-1.1.0.phar
  - curl -sSfL -o phpunit.phar https://phar.phpunit.de/phpunit-7.4.3.phar

before_script:
  - php composer.phar install
  - php composer.phar dump-autoload

script:
  - php phpunit.phar --configuration ./phpunit.xml
  - php -d phar.readonly=off ./phar-composer.phar build . ./bin/everimg.phar
