name: actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: download composer.phar
        run: curl -sSfL -o composer.phar https://getcomposer.org/composer-stable.phar

      - name: download phar-composer.phar
        run: curl -sSfL -o phar-composer.phar https://github.com/clue/phar-composer/releases/download/v1.1.0/phar-composer-1.1.0.phar

      - name: download phpunit.phar
        run: curl -sSfL -o phpunit.phar https://phar.phpunit.de/phpunit-7.4.3.phar

      - name: composer.phar install
        run: php composer.phar install

      - name: composer.phar dump-autoload
        run: php composer.phar dump-autoload

      - name: test
        run: php phpunit.phar --configuration ./phpunit.xml

      - name: build
        run: php -d phar.readonly=off ./phar-composer.phar build . ./bin/everimg.phar
